# Readme

Garfield Naruto encoder is a simplified prototype of an encoder which is design to hide bit strings inside of text in a way that is hard to detect using statistical tests. You can review the [website](localhost) to learn more information on applications and the security parameters. The long term goal of this project is to be able to allow communication of private information on public platforms to bypass surveillance and state discrimination, if you are interested in supporting this please consider contributing funding on our website.

### WARNING -- This repo is a simple prototype and should not be used for ANY privacy critical application with high stakes.

## How it works

In each character of an output text is one of the possible signals {0, 1, SKIP} and these buckets of characters are selected using randomness sampled from a hash of a private key and the position. The model must choose either the correct bit or a skip in each position, which we implement by changing the probability values of each token output. The model samples up to the sentence boundary of tokens over multiple tries then selects an output which has the lowest surprise and highest fluency score. The outputs can then be decoded by any user without needing the model using the private key, in contrast to other text embedding models. 

## Requirements

- **Apple Silicon Mac.** Generation runs on MLX, which is Metal-only. Decoding has no such requirement — it needs only the text and the key.
- **Python 3.10+** and **Node 18+** (Node is only needed for the website's helper server).

## Install

```
python3 -m venv ~/.venvs/stego
~/.venvs/stego/bin/pip install mlx-lm unishox2-py3
```

`mlx-lm` pulls in `mlx`, `numpy` and `transformers`. `unishox2-py3` is only needed for `--message`; hiding a raw bitstream with `--bits` works without it.

The model is downloaded from Hugging Face on first run and cached in `~/.cache/huggingface`. The default is `mlx-community/SmolLM3-3B-8bit` (~3 GB). On a smaller machine, pass `--model mlx-community/SmolLM2-360M-Instruct-6bit` (~300 MB) — it is several times faster, with noticeably weaker prose.

## Command line

Hide a message:

```
~/.venvs/stego/bin/python sentence_encode.py --topic "the sea" --message "meet at dawn" --key hunter2
```

Hide a raw bitstream, printing only the cover text:

```
~/.venvs/stego/bin/python sentence_encode.py --topic "the sea" --bits 10110100 --key hunter2 --clean
```

`--clean` streams each sentence as it is committed and suppresses everything else; the exit code still reports whether the payload verified. `--help` lists the rest.

## Website

The page works three ways, and needs no build step.

**Decoding is pure JavaScript.** It walks the characters with the key and never
touches the model, so it works with no server and no GPU — open `index.html`,
paste cover text and the key, press DECODE.

**Encoding is embedded from a Hugging Face Space**, because it needs the model.
GPU time is billed to whoever runs it. Note that browsers restrict cookies in a
cross-site frame, so Hugging Face cannot see a visitor's session there and falls
back to a small pool shared by IP address; opening the Space in its own tab,
signed in, uses their own quota instead.

That makes the page deployable as a **static site** — `index.html`, `style.css`,
`script.js` and `unishox2.js`, on any static host.

**Encoding locally is still available** when you want your own model rather than
the hosted one. Start the helper and the page reveals a local encode block; it
stays hidden otherwise, which is why the deployed site never shows it. Point it
at the interpreter that has `mlx-lm` installed:

```
PYTHON=~/.venvs/stego/bin/python node server.js
```

It listens on `http://localhost:3000` and runs `sentence_encode.py` in the directory `server.js` lives in. A bare `node server.js` uses whatever `python3` is on your PATH, which is usually the system Python and will fail with `ModuleNotFoundError: No module named 'numpy'`.

Then open `index.html`. Fill in Message, Topic and Key under "Run it locally
instead" and press **Begin Encoding**; output streams in live over Server-Sent
Events, and **Stop** kills the running process.

The server exposes only `/stream-command` and `/stop-command`. It does not serve
the page itself, which is why `script.js` is a classic script rather than an ES
module: browsers block module loading over `file://`.

## Tests

```
~/.venvs/stego/bin/python test_sentence_encode.py   # constraint, round-trip, cache — no model needed
node verify_js_decoder.mjs                          # JS decoder agrees with the Python encoder
```

The first stubs out MLX, so it runs in milliseconds on any machine. The second checks the browser decoder against vectors generated by the Python side, so the two implementations cannot drift apart.
