/*
 * verify_js_decoder.mjs — proves the browser decoder in script.js agrees with
 * the Python encoder.
 *
 *   node verify_js_decoder.mjs
 *
 * Vectors below were generated by the Python side (simple_encode.extract and
 * payload_codec.compress_to_bits), so this checks against the real codec rather
 * than against another JavaScript implementation of the same idea.
 *
 * script.js is a classic browser script, not a module, so it is loaded here the
 * way the page loads it: unishox2.js first, then script.js, sharing one global
 * scope, with a stub DOM so the page wiring does not throw.
 */
import fs from "node:fs";
import vm from "node:vm";

const VECTORS = {
  "texts": [
    "The waves whispered secrets to the seashore.",
    "Café niño — accents, digits 123 and punctuation!",
    "Perch would bide near his wrist, counting each taut tick."
  ],
  "roles": {
    "demo": [
      [
        2,
        1,
        1,
        1,
        0,
        2,
        2,
        0,
        2,
        1,
        1,
        2,
        1,
        1,
        2,
        0,
        2,
        1,
        0,
        1,
        0,
        0,
        0,
        1,
        0,
        1
      ],
      [
        1,
        2,
        2,
        2,
        0,
        0,
        2,
        2,
        1,
        0,
        0,
        0,
        1,
        2,
        0,
        1,
        1,
        2,
        0,
        1,
        2,
        1,
        0,
        0,
        1,
        2
      ],
      [
        1,
        0,
        0,
        0,
        1,
        0,
        0,
        2,
        2,
        2,
        2,
        0,
        2,
        2,
        2,
        2,
        2,
        0,
        1,
        0,
        1,
        1,
        0,
        0,
        1,
        1
      ]
    ],
    "harbor-lantern": [
      [
        1,
        2,
        2,
        2,
        1,
        1,
        0,
        2,
        2,
        1,
        2,
        1,
        1,
        0,
        1,
        0,
        2,
        2,
        0,
        0,
        1,
        2,
        0,
        0,
        0,
        1
      ],
      [
        2,
        1,
        1,
        0,
        1,
        0,
        0,
        2,
        2,
        0,
        1,
        0,
        2,
        0,
        1,
        2,
        1,
        2,
        1,
        0,
        0,
        0,
        0,
        2,
        2,
        2
      ],
      [
        1,
        2,
        0,
        2,
        2,
        1,
        2,
        0,
        1,
        1,
        1,
        2,
        1,
        0,
        0,
        0,
        2,
        2,
        0,
        1,
        1,
        0,
        2,
        2,
        2,
        1
      ]
    ]
  },
  "bits": {
    "demo|0": [
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1
    ],
    "demo|1": [
      1,
      1,
      0,
      1,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      1,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      0
    ],
    "demo|2": [
      0,
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      1,
      0,
      0,
      1,
      0,
      1,
      1,
      0,
      1,
      1,
      1,
      0
    ],
    "harbor-lantern|0": [
      0,
      1,
      1,
      0,
      1,
      1,
      1,
      1,
      1,
      0,
      1,
      1,
      1,
      1,
      0,
      0,
      0,
      0,
      1,
      0,
      1
    ],
    "harbor-lantern|1": [
      1,
      0,
      1,
      0,
      1,
      1,
      0,
      0,
      0,
      1,
      1,
      0,
      1,
      0,
      0,
      1,
      0,
      1,
      1,
      1,
      0
    ],
    "harbor-lantern|2": [
      0,
      1,
      1,
      0,
      0,
      0,
      0,
      0,
      1,
      1,
      0,
      0,
      1,
      0,
      1,
      0,
      1,
      1,
      1,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      1,
      0,
      1
    ]
  },
  "frames": {
    "meet at dawn": "000011000000011111111001011011100001010011000010111010100111110111110000",
    "don’t be late": "000011110000101011110101010110000111110000111111011001100001011110100110101110001001100001100101",
    "café at dawn": "000011010000101011110011001111110000011110000001010100101010011000010111010100111110111110000101"
  }
};

function loadBrowserScripts() {
  const els = {};
  const mk = () => ({ value: "", textContent: "", _h: null,
                      addEventListener(_, h) { this._h = h; },
                      click() { if (this._h) this._h(); },
                      scrollTop: 0, scrollHeight: 0 });
  const ctx = { TextEncoder, console,
                document: { getElementById: (id) => (els[id] ??= mk()) },
                EventSource: function () {}, fetch: () => Promise.resolve() };
  ctx.window = ctx;
  vm.createContext(ctx);
  for (const f of ["unishox2.js", "script.js"]) {
    vm.runInContext(fs.readFileSync(f, "utf8"), ctx, { filename: f });
  }
  return { ctx, els };
}

const { ctx } = loadBrowserScripts();
const charRole = vm.runInContext("charRole", ctx);
const decodeBits = vm.runInContext("decodeBits", ctx);
const decodeMessage = vm.runInContext("decodeMessage", ctx);
const bitsToBytes = vm.runInContext("bitsToBytes", ctx);

let checks = 0, fail = 0;
const ok = (cond, msg) => { checks++; if (!cond) { fail++; console.log("  FAIL " + msg); } };

// 1. keyed role tables
for (const [key, table] of Object.entries(VECTORS.roles)) {
  for (let pos = 0; pos < table.length; pos++) {
    for (let i = 0; i < 26; i++) {
      ok(charRole("abcdefghijklmnopqrstuvwxyz"[i], pos, key) === table[pos][i],
         `role key=${key} pos=${pos} letter=${i}`);
    }
  }
}
console.log(`key schedule : ${checks} checks, ${fail} failures`);

// 2. bit extraction, including accents and punctuation
let before = fail;
for (const [k, want] of Object.entries(VECTORS.bits)) {
  const [key, idx] = k.split("|");
  const got = decodeBits(VECTORS.texts[+idx], key);
  ok(got.length === want.length && got.every((v, i) => v === want[i]), `extract(${k})`);
}
console.log(`extract()    : ${Object.keys(VECTORS.bits).length} texts, ${fail - before} failures`);

// 3. the message layer, via unishox2.js. Non-ASCII is included on purpose: the
//    frame's size field is a UTF-8 byte count while a JS string's .length counts
//    UTF-16 units, and comparing those directly once rejected valid decodes.
before = fail;
for (const [msg, frameBits] of Object.entries(VECTORS.frames)) {
  const bits = [...frameBits].map(Number);
  const data = bitsToBytes(bits);
  // decodeMessage takes cover text, so exercise the frame path directly here by
  // stubbing a text whose extracted bits are exactly this frame is not possible;
  // instead check the codec round-trip that decodeMessage relies on.
  let i = 0;
  const varint = () => { let n = 0, s = 0; for (;;) { const b = data[i++];
    n |= (b & 0x7f) << s; if (!(b & 0x80)) return n; s += 7; } };
  const originalSize = varint(), compLen = varint();
  const out = vm.runInContext("unishox2_decompress_simple", ctx)(
    data.slice(i, i + compLen), compLen);
  ok(out === msg, `message ${JSON.stringify(msg)} -> ${JSON.stringify(out)}`);
  ok(new TextEncoder().encode(out).length === originalSize,
     `byte-length check for ${JSON.stringify(msg)}`);
}
console.log(`messages     : ${Object.keys(VECTORS.frames).length} payloads, ${fail - before} failures`);

console.log(fail === 0 ? "\nALL CHECKS PASSED" : `\n${fail} FAILURES`);
process.exit(fail === 0 ? 0 : 1);
